# Generated by Django 3.2.5 on 2021-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='마이페이지에서 이름을 입력해주세요!', max_length=60, verbose_name='email'),
        ),
    ]
