# Generated by Django 3.2.5 on 2021-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/Bin.png', max_length=255, null=True, upload_to='img/'),
        ),
    ]
