# Generated by Django 3.2.5 on 2021-07-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage_finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='sub_section',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
