# Generated by Django 3.2.5 on 2021-07-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief_description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
