# Generated by Django 3.2.5 on 2021-07-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0002_auto_20210720_0256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPage_finance',
        ),
        migrations.DeleteModel(
            name='MainPage_section',
        ),
    ]
